// Companies Data for Bucharest Job Search
const companies = [
    // TIER 1: HIGHEST PRIORITY
    {
        name: "UiPath",
        type: "RPA & AI Automation",
        size: "1,000+ Romania",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4495, lng: 26.0803 },
        address: "4 Vasile Alecsandri St, Sector 1, 010638",
        metro: "Piața Victoriei (M1/M2)",
        commute: "35-45 min",
        ai: true,
        visa: "YES - Established",
        remote: "Hybrid (2 days)",
        hr: "TALeaders@uipath.com",
        careers: "https://careers.uipath.com",
        linkedin: "https://linkedin.com/company/uipath",
        glassdoor: "https://glassdoor.com/Overview/Working-at-UiPath",
        description: "Romanian unicorn, NYSE listed, RPA leader with extensive AI/ML work"
    },
    {
        name: "Bitdefender",
        type: "Cybersecurity",
        size: "1,350+ Romania",
        categories: ["tier1", "cybersecurity", "short-commute"],
        priority: true,
        location: { lat: 44.4389, lng: 26.0478 },
        address: "15A Soseaua Orhideelor, Orhideea Towers, Floors 10-12",
        metro: "Grozavesti (M3) - Direct tunnel",
        commute: "15-20 min ⭐",
        ai: true,
        visa: "YES - Global company",
        remote: "Hybrid",
        hr: "recruitment@bitdefender.com",
        careers: "https://bitdefender.com/company/careers",
        linkedin: "https://linkedin.com/company/bitdefender",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Bitdefender",
        description: "Global cybersecurity leader, C++ roles, shortest commute!"
    },
    {
        name: "Amazon / AWS",
        type: "Cloud Computing",
        size: "1,650+ Bucharest",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4937, lng: 26.1405 },
        address: "Globalworth Campus, 4-6 Dimitrie Pompeiu Blvd",
        metro: "Pipera (M2) - 50m",
        commute: "35-40 min",
        ai: true,
        visa: "YES - Standard Amazon",
        remote: "Hybrid",
        hr: "amazon.jobs/bucharest",
        careers: "https://amazon.jobs",
        linkedin: "https://linkedin.com/company/amazon",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Amazon",
        description: "World's largest cloud provider, extensive AI/ML work"
    },
    {
        name: "Oracle Romania",
        type: "Enterprise Software",
        size: "3,000+ Romania",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4776, lng: 26.1108 },
        address: "Sky Tower, Floors 23-31, 246C Calea Floreasca",
        metro: "Aurel Vlaicu (M2)",
        commute: "30-40 min",
        ai: true,
        visa: "YES - Established",
        remote: "Hybrid",
        hr: "careers.oracle.com",
        careers: "https://oracle.com/careers",
        linkedin: "https://linkedin.com/company/oracle",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Oracle",
        description: "Enterprise software giant, 9 floors in Sky Tower"
    },
    {
        name: "Microsoft Romania",
        type: "Tech Support & Engineering",
        size: "500+ Romania",
        categories: ["tier1", "ai", "short-commute"],
        priority: true,
        location: { lat: 44.4360, lng: 26.0430 },
        address: "Bulevardul Iuliu Maniu 6P, Campus 6.2",
        metro: "Grozăvești (M3)",
        commute: "20-25 min",
        ai: true,
        visa: "YES - Comprehensive",
        remote: "Hybrid",
        hr: "careers.microsoft.com",
        careers: "https://microsoft.com/careers",
        linkedin: "https://linkedin.com/company/microsoft",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Microsoft",
        description: "Tech support, Azure AI, near Chiajna"
    },
    {
        name: "IBM Romania",
        type: "IT Services",
        size: "2,650+ Romania",
        categories: ["tier1", "ai", "short-commute"],
        priority: true,
        location: { lat: 44.4395, lng: 26.0480 },
        address: "Orhideea 15D, The Bridge, Building A",
        metro: "Grozavesti (M3)",
        commute: "15-20 min",
        ai: true,
        visa: "YES - International",
        remote: "Hybrid",
        hr: "ibm.com/careers",
        careers: "https://ibm.com/employment",
        linkedin: "https://linkedin.com/company/ibm",
        glassdoor: "https://glassdoor.com/Overview/Working-at-IBM",
        description: "Watson AI, global IT services"
    },
    {
        name: "Adobe Romania",
        type: "Creative Software",
        size: "1,200+ (EMEA R&D)",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4010, lng: 26.1250 },
        address: "Calea Serban Voda 206-218, U-Center 2",
        metro: "Various",
        commute: "35-45 min",
        ai: true,
        visa: "YES - Major multinational",
        remote: "Hybrid",
        hr: "adobe.com/careers",
        careers: "https://adobe.com/careers",
        linkedin: "https://linkedin.com/company/adobe",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Adobe",
        description: "Largest EMEA R&D center, Adobe Sensei AI"
    },
    {
        name: "Google Romania",
        type: "Product Development",
        size: "350-377",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4262, lng: 26.1025 },
        address: "Unirii View + Fitbit hub",
        metro: "Piața Unirii",
        commute: "35-45 min",
        ai: true,
        visa: "YES - Standard relocation",
        remote: "Hybrid",
        hr: "google.com/careers",
        careers: "https://careers.google.com",
        linkedin: "https://linkedin.com/company/google",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Google",
        description: "Fitbit wearables, health algorithms"
    },
    {
        name: "EPAM Systems",
        type: "IT Services",
        size: "62,050+ global",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4500, lng: 26.1000 },
        address: "Crystal Tower, 9th Floor",
        metro: "Various",
        commute: "30-40 min",
        ai: true,
        visa: "YES - 55+ countries",
        remote: "Hybrid/Remote",
        hr: "epam.com/careers",
        careers: "https://epam.com/careers",
        linkedin: "https://linkedin.com/company/epam-systems",
        glassdoor: "https://glassdoor.com/Overview/Working-at-EPAM-Systems",
        description: "Digital transformation, many openings"
    },
    {
        name: "Endava",
        type: "Digital Transformation",
        size: "11,000+ global",
        categories: ["tier1", "ai"],
        priority: true,
        location: { lat: 44.4715, lng: 26.0926 },
        address: "Green Court A, 2 Gara Herastrau",
        metro: "Aviatorilor (M2)",
        commute: "35-45 min",
        ai: true,
        visa: "YES - Global operations",
        remote: "Hybrid",
        hr: "careers.endava.com",
        careers: "https://endava.com/careers",
        linkedin: "https://linkedin.com/company/endava",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Endava",
        description: "NYSE listed, DevOps openings"
    },

    // ROMANIAN HIGH-GROWTH
    {
        name: "DRUID AI",
        type: "Conversational AI",
        size: "170+ global",
        categories: ["romanian", "ai"],
        priority: false,
        location: { lat: 44.4500, lng: 26.0850 },
        address: "Bucharest offices",
        metro: "TBD",
        commute: "TBD",
        ai: true,
        visa: "Likely YES - US based",
        remote: "Hybrid",
        hr: "druidai.com/careers",
        careers: "https://druidai.com/careers",
        linkedin: "https://linkedin.com/company/druid-ai",
        glassdoor: "https://glassdoor.com/Overview/Working-at-DRUID",
        description: "Series C €25M, AI agents platform"
    },
    {
        name: "FLOWX.AI",
        type: "Banking AI Platform",
        size: "50-200",
        categories: ["romanian", "ai", "fintech"],
        priority: false,
        location: { lat: 44.4715, lng: 26.0926 },
        address: "Charles de Gaulle Plaza",
        metro: "Aviatorilor (M2)",
        commute: "35-40 min",
        ai: true,
        visa: "Possible - International",
        remote: "Hybrid",
        hr: "flowx.ai/careers",
        careers: "https://flowx.ai/careers",
        linkedin: "https://linkedin.com/company/flowxai",
        glassdoor: "https://glassdoor.com/Overview/Working-at-FLOWX-AI",
        description: "Series A $43.5M, fintech AI"
    },
    {
        name: "FintechOS",
        type: "Fintech Platform",
        size: "350+ global",
        categories: ["romanian", "fintech", "ai"],
        priority: false,
        location: { lat: 44.4920, lng: 26.1410 },
        address: "Oregon Park, 46-48 Pipera Rd",
        metro: "Pipera (M2)",
        commute: "35-40 min",
        ai: true,
        visa: "Likely YES - London/NYC",
        remote: "Hybrid",
        hr: "careers@fintechos.com",
        careers: "https://fintechos.com/careers",
        linkedin: "https://linkedin.com/company/fintechos",
        glassdoor: "https://glassdoor.com/Overview/Working-at-FintechOS",
        description: "Banks/insurance, €10B assets"
    },
    {
        name: "Tremend",
        type: "Software Development",
        size: "500-600 Romania",
        categories: ["romanian", "ai"],
        priority: false,
        location: { lat: 44.4192, lng: 26.1215 },
        address: "165 Splaiul Unirii, Timpuri Noi",
        metro: "Timpuri Noi (M1)",
        commute: "25-35 min",
        ai: true,
        visa: "Check - 14+ countries",
        remote: "Hybrid/Remote",
        hr: "tremend.com/careers",
        careers: "https://tremend.com/careers",
        linkedin: "https://linkedin.com/company/tremend",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Tremend",
        description: "Publicis Sapient, AI/ML, GenAI"
    },

    // CYBERSECURITY
    {
        name: "Thales Romania",
        type: "Aerospace/Defense Tech",
        size: "Large",
        categories: ["cybersecurity", "short-commute"],
        priority: false,
        location: { lat: 44.4390, lng: 26.0479 },
        address: "Orhideea Towers",
        metro: "Grozavesti (M3)",
        commute: "15-20 min",
        ai: true,
        visa: "YES - Global French",
        remote: "Hybrid",
        hr: "thalesgroup.com/careers",
        careers: "https://thalesgroup.com/careers",
        linkedin: "https://linkedin.com/company/thales",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Thales",
        description: "Defense tech, same area as Bitdefender"
    },
    {
        name: "CrowdStrike",
        type: "Cybersecurity",
        size: "Global",
        categories: ["cybersecurity"],
        priority: false,
        location: { lat: 44.4500, lng: 26.1000 },
        address: "Bucharest office",
        metro: "TBD",
        commute: "TBD",
        ai: true,
        visa: "YES - NASDAQ listed",
        remote: "Hybrid",
        hr: "crowdstrike.com/careers",
        careers: "https://crowdstrike.com/careers",
        linkedin: "https://linkedin.com/company/crowdstrike",
        glassdoor: "https://glassdoor.com/Overview/Working-at-CrowdStrike",
        description: "C/C++ kernel development, endpoint security"
    },

    // FINTECH
    {
        name: "ING Hubs Romania",
        type: "Banking Technology",
        size: "1,000+",
        categories: ["fintech", "ai"],
        priority: false,
        location: { lat: 44.4776, lng: 26.1108 },
        address: "246C Calea Floreasca",
        metro: "Aurel Vlaicu (M2)",
        commute: "30-40 min",
        ai: true,
        visa: "YES - Global bank",
        remote: "Hybrid",
        hr: "ing.jobs/romania",
        careers: "https://ing.jobs/romania",
        linkedin: "https://linkedin.com/company/ing-hubs-romania",
        glassdoor: "https://glassdoor.com/Overview/Working-at-ING",
        description: "Tech hub for ING Bank, DevOps roles"
    },
    {
        name: "Raiffeisen Bank Tech",
        type: "Banking Technology",
        size: "Large",
        categories: ["fintech", "ai"],
        priority: false,
        location: { lat: 44.4780, lng: 26.1105 },
        address: "Sky Tower area",
        metro: "Aurel Vlaicu (M2)",
        commute: "30-40 min",
        ai: true,
        visa: "YES - Global bank",
        remote: "Hybrid",
        hr: "raiffeisen.ro/careers",
        careers: "https://raiffeisen.ro/careers",
        linkedin: "https://linkedin.com/company/raiffeisen-bank-romania",
        glassdoor: "https://glassdoor.com/Overview/Working-at-Raiffeisen",
        description: "Banking technology hub"
    }
];

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = companies;
}
